# Generated by Django 4.2.3 on 2023-07-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('previous_state', models.CharField(max_length=50)),
                ('previous_division', models.CharField(max_length=2)),
                ('estimate', models.IntegerField()),
                ('margin_of_error', models.FloatField()),
            ],
        ),
    ]
